import type { Race } from "@prisma/client";

export type ClanTierSeedEntry = {
  nickname: string;
  race: Race;
  tier: number;
};

/** 나무클랜 공식 티어표 — 1~5티어 배치 명단 (미배치 제외) */
export const NAMU_CLAN_TIER_MEMBERS: ClanTierSeedEntry[] = [
  { nickname: "Cap", race: "Z", tier: 1 },
  { nickname: "Louie", race: "Z", tier: 2 },
  { nickname: "momo", race: "Z", tier: 2 },
  { nickname: "MamBa", race: "Z", tier: 2 },
  { nickname: "Creative", race: "Z", tier: 2 },
  { nickname: "Panic", race: "Z", tier: 2 },
  { nickname: "Suntory", race: "Z", tier: 2 },
  { nickname: "Rakan", race: "Z", tier: 2 },
  { nickname: "rOrO", race: "Z", tier: 2 },
  { nickname: "Forreal", race: "Z", tier: 3 },
  { nickname: "Scarlet", race: "Z", tier: 3 },
  { nickname: "Sooharm", race: "Z", tier: 3 },
  { nickname: "Bullfrog", race: "Z", tier: 3 },
  { nickname: "Pray", race: "Z", tier: 3 },
  { nickname: "Banbek", race: "Z", tier: 3 },
  { nickname: "Paramedic", race: "Z", tier: 4 },
  { nickname: "Bingbyuk", race: "Z", tier: 4 },
  { nickname: "Bulnak", race: "Z", tier: 4 },
  { nickname: "Sunbi", race: "Z", tier: 4 },
  { nickname: "Yellow", race: "Z", tier: 4 },
  { nickname: "Play", race: "Z", tier: 4 },
  { nickname: "Wiki", race: "Z", tier: 5 },
  { nickname: "Jinp", race: "Z", tier: 5 },
  { nickname: "One2", race: "Z", tier: 5 },
  { nickname: "Cool", race: "Z", tier: 5 },
  { nickname: "Moozzi2", race: "Z", tier: 5 },
  { nickname: "BingBing", race: "Z", tier: 5 },
  { nickname: "Nabi", race: "T", tier: 1 },
  { nickname: "Palette", race: "T", tier: 1 },
  { nickname: "Hungry", race: "T", tier: 1 },
  { nickname: "GG", race: "T", tier: 1 },
  { nickname: "Dicouser", race: "T", tier: 1 },
  { nickname: "Bulldozer", race: "T", tier: 2 },
  { nickname: "Babi", race: "T", tier: 2 },
  { nickname: "ID4885", race: "T", tier: 2 },
  { nickname: "JY", race: "T", tier: 2 },
  { nickname: "Baebab", race: "T", tier: 2 },
  { nickname: "Comeback", race: "T", tier: 2 },
  { nickname: "Coru2", race: "T", tier: 2 },
  { nickname: "Kwonwang", race: "T", tier: 2 },
  { nickname: "Morimoto", race: "T", tier: 2 },
  { nickname: "Yacharule", race: "T", tier: 2 },
  { nickname: "Green", race: "T", tier: 3 },
  { nickname: "P.O", race: "T", tier: 3 },
  { nickname: "Alphago", race: "T", tier: 3 },
  { nickname: "Soa", race: "T", tier: 3 },
  { nickname: "iikko", race: "T", tier: 4 },
  { nickname: "Kasha", race: "T", tier: 4 },
  { nickname: "Hoy", race: "T", tier: 4 },
  { nickname: "FO", race: "T", tier: 4 },
  { nickname: "Doy", race: "T", tier: 4 },
  { nickname: "Terran", race: "T", tier: 4 },
  { nickname: "Toy", race: "T", tier: 4 },
  { nickname: "Wai", race: "T", tier: 5 },
  { nickname: "Naknal", race: "T", tier: 5 },
  { nickname: "Shield", race: "P", tier: 1 },
  { nickname: "Volvo", race: "P", tier: 1 },
  { nickname: "Fork", race: "P", tier: 1 },
  { nickname: "Polpo", race: "P", tier: 1 },
  { nickname: "Heeyoung", race: "P", tier: 1 },
  { nickname: "Havoc", race: "P", tier: 2 },
  { nickname: "Younha", race: "P", tier: 2 },
  { nickname: "Swan", race: "P", tier: 2 },
  { nickname: "CL", race: "P", tier: 2 },
  { nickname: "Fu", race: "P", tier: 2 },
  { nickname: "Best", race: "P", tier: 2 },
  { nickname: "Icebeer", race: "P", tier: 3 },
  { nickname: "Thrill", race: "P", tier: 3 },
  { nickname: "Podori", race: "P", tier: 3 },
  { nickname: "Work", race: "P", tier: 3 },
  { nickname: "DanDan", race: "P", tier: 3 },
  { nickname: "HH", race: "P", tier: 3 },
  { nickname: "Whatthe", race: "P", tier: 3 },
  { nickname: "Honeybadger", race: "P", tier: 3 },
  { nickname: "Chan", race: "P", tier: 3 },
  { nickname: "This9", race: "P", tier: 3 },
  { nickname: "River", race: "P", tier: 3 },
  { nickname: "Lightseek", race: "P", tier: 4 },
  { nickname: "Frosty", race: "P", tier: 4 },
  { nickname: "Lyougi-siki", race: "P", tier: 4 },
  { nickname: "Dondon", race: "P", tier: 4 },
  { nickname: "Closer", race: "P", tier: 4 },
  { nickname: "Jaehee3017", race: "P", tier: 4 },
  { nickname: "Star", race: "P", tier: 4 },
  { nickname: "Bola", race: "P", tier: 4 },
  { nickname: "Killer", race: "P", tier: 4 },
  { nickname: "Rooney", race: "P", tier: 5 },
  { nickname: "Potatoss", race: "P", tier: 5 },
  { nickname: "Gulchus", race: "P", tier: 5 },
  { nickname: "Ddajo", race: "P", tier: 5 },
  { nickname: "Heulgsin", race: "P", tier: 5 },
  { nickname: "Mateo", race: "P", tier: 5 },
  { nickname: "Pikachu", race: "P", tier: 5 },
  { nickname: "GS", race: "P", tier: 5 },
  { nickname: "Onkel", race: "P", tier: 5 },
  { nickname: "Attack", race: "P", tier: 5 },
  { nickname: "Passion", race: "P", tier: 5 },
  { nickname: "Neta", race: "P", tier: 5 },
  { nickname: "Noel", race: "P", tier: 5 },
];
